const data = {
  products: [
    {
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      image: "/images/p1.jpg",
      category: "shirts",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: "10 reviews",
      description: "high quality product",
    },
    {
      name: "Adidas Slim Shirt",
      slug: "adidas-slim-shirts",
      image: "/images/p2.jpg",
      category: "pants",
      price: 120,
      countInStock: 0,
      brand: "Nike",
      rating: 4.5,
      numReviews: "10 reviews",
      description: "high quality pants",
    },
    {
      name: "Adidas Slim Pant",
      slug: "adidas-slim-shirt",
      image: "/images/p3.jpg",
      category: "pants",
      price: 120,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: "10 reviews",
      description: "high quality product",
    },
    {
      name: "Puma Slim shirt",
      slug: "puma-slim-shirt",
      image: "/images/p4.jpg",
      category: "shirt",
      price: 120,
      countInStock: 10,
      brand: "Puma",
      rating: 3.5,
      numReviews: "10 reviews",
      description: "high quality product",
    },
  ],
};

export default data;
